/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Fungsi.Koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hoerzz
 */
public class GajiTambahan extends javax.swing.JFrame {
    private final DefaultTableModel tabModel;

    /**
     * Creates new form Pemasukkan
     */
    public GajiTambahan() {
        initComponents();
        setLocationRelativeTo(null);
        new Fungsi.Koneksi().koneksiDatabase();
        String[] row = {"Kode","Tanggal","Nama Karyawan","Keterangan","Nilai"};
        tabModel = new DefaultTableModel(null,row);
        tbPemasukkan.setModel(tabModel);
        dcTanggal.setDate(new java.util.Date()); 
        tampilDataKeTabel();
        DataKaryawan();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    private void DataKaryawan()
    {
        try {
          PreparedStatement prestat = Koneksi.konek.prepareStatement("SELECT nmkaryawan FROM data_karyawan");
          ResultSet rs = prestat.executeQuery();
          n_karyawan.removeAllItems();
          
          while(rs.next())
          {
              String name = rs.getString("nmkaryawan");
              n_karyawan.addItem(name);
          }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void tampilDataKeTabel(){
        try {
            String sql = "select * from gajikaryawan where jenisgaji = 'Gaji Tambahan' ORDER BY `tanggal` ASC";
            Statement stat = new Fungsi.Koneksi().konek.createStatement();
            ResultSet res = stat.executeQuery(sql);
          
            while(res.next()){
                String kode = res.getString("id");
                String tanggal = res.getString("tanggal");
                String nama = res.getString("nama_karyawan");
                String keterangan = res.getString("keterangan");
                String jumlah = res.getString("jumlah");
                String data[] = {kode,tanggal,nama,keterangan,jumlah};
                tabModel.addRow(data);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void hapusPadaForm(){
        int row = tabModel.getRowCount();
        for (int i = 0; i < row; i++) {
            tabModel.removeRow(0);
        }
    }
    
    private void getDataFromTable() throws ParseException{
        int i = this.tbPemasukkan.getSelectedRow();
        if (i==-1) {
            return ;
        }
        String kode = (String) tabModel.getValueAt(i, 0);
        String tanggal = (String) tabModel.getValueAt(i, 1);
        String nama = (String) tabModel.getValueAt(i, 2);
        String keterangan = (String) tabModel.getValueAt(i, 3);
        String jumlah = (String) tabModel.getValueAt(i, 4);
        
        tfKode.setText(kode);
        Date date=new SimpleDateFormat("yyyy-MM-dd").parse(tanggal); 
        dcTanggal.setDate(date);
        n_karyawan.setSelectedItem(nama);
        tfKeterangan.setText(keterangan);
        tfJumlah.setText(jumlah);
        
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        keyType();
    }
    
    private void keyType(){
        if (!(tfKeterangan.getText().equals(""))&&!(tfJumlah.getText().equals(""))) {
            btnSimpan.setEnabled(true);
            btnBatal.setEnabled(true);
        }
    }
    
    private void hapus(){
        tfKode.setText("");
        n_karyawan.setSelectedIndex(-1);
        tfKeterangan.setText("");
        tfJumlah.setText("");
        dcTanggal.setDate(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfJumlah = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfKode = new javax.swing.JTextField();
        dcTanggal = new com.toedter.calendar.JDateChooser();
        tfKeterangan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        n_karyawan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPemasukkan = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CV.Bumi Indah :: Gaji Tambahan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Tanggal");

        tfJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfJumlahKeyTyped(evt);
            }
        });

        jLabel2.setText("Nama Karyawan");

        jLabel3.setText("Jumlah Tambahan");

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Modify.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Close.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Erase.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setEnabled(false);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel4.setText("Kode");

        tfKode.setEditable(false);

        dcTanggal.setDateFormatString("yyyy-MM-dd");

        tfKeterangan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfKeteranganPropertyChange(evt);
            }
        });

        jLabel5.setText("Keterangan");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Vista_icons_09.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfKode)
                            .addComponent(dcTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfKeterangan)
                            .addComponent(n_karyawan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfJumlah)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfKode)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(dcTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(n_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal))
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        tbPemasukkan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbPemasukkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPemasukkanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPemasukkan);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logo-removebg-preview (1).png"))); // NOI18N
        jLabel6.setText("CV. Bumi Indah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (!(tfJumlah.getText().equals(""))&&!(n_karyawan.getSelectedItem().equals(""))) {
            try {
                String sql = "INSERT INTO `gajikaryawan` (`tanggal`, `nama_karyawan`, `keterangan`, `jumlah`, `jenisgaji`, `hitung`) VALUES (?, ?, ?, ?, 'Gaji Tambahan', ?);";
                PreparedStatement prestat = new Fungsi.Koneksi().konek.prepareStatement(sql);
                String date=new SimpleDateFormat("yyyy-MM-dd").format(dcTanggal.getDate());
                prestat.setString(1,date);
                prestat.setString(2, n_karyawan.getSelectedItem().toString());
                prestat.setString(3,tfKeterangan.getText());
                prestat.setString(4,tfJumlah.getText());
                prestat.setString(5,tfJumlah.getText());
                prestat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data telah disimpan","Informasi",JOptionPane.INFORMATION_MESSAGE);
                hapusPadaForm();
                tampilDataKeTabel();
                hapus(); 
            } catch (Exception e) {
                System.out.println(""+e);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Data harus diisi!","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        tfKode.setText("");
        n_karyawan.setSelectedIndex(-1);
        tfKeterangan.setText("");
        tfJumlah.setText("");
        dcTanggal.setDate(null); 
        keyType();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tbPemasukkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPemasukkanMouseClicked
        try {
            // TODO add your handling code here:
            getDataFromTable();
        } catch (ParseException ex) {
            Logger.getLogger(GajiTambahan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbPemasukkanMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (!(tfJumlah.getText().equals(""))&&!( n_karyawan.getSelectedItem().equals(""))) {
            try {
                String sql = "UPDATE gajikaryawan SET nama_karyawan = ?,keterangan = ?, jumlah = ?, tanggal = ? ,hitung = ? WHERE id = "+tfKode.getText();
                PreparedStatement prestat = new Fungsi.Koneksi().konek.prepareStatement(sql);
                prestat.setString(1,n_karyawan.getSelectedItem().toString());
                prestat.setString(2,tfKeterangan.getText());
                prestat.setString(3,tfJumlah.getText());
                String date=new SimpleDateFormat("yyyy-MM-dd").format(dcTanggal.getDate()); 
                prestat.setString(4, date);
                prestat.setInt(5, (Integer.parseInt(tfJumlah.getText())*-1));
                prestat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data telah diedit","Informasi",JOptionPane.INFORMATION_MESSAGE);
                hapusPadaForm();
                tampilDataKeTabel();
                hapus(); 
            } catch (Exception e) {
                System.out.println(""+e);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Data harus diisi!","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            if (JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus?","warning", 2)== JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM gajikaryawan WHERE id ="+tfKode.getText();
                Statement stat = new Fungsi.Koneksi().konek.createStatement();
                int hasil = stat.executeUpdate(sql);
                
                if (hasil == 1) {
                    JOptionPane.showMessageDialog(null, "Data telah dihapus","Informasi",JOptionPane.INFORMATION_MESSAGE);
                }
                hapusPadaForm();
                tampilDataKeTabel();
                
            }
        } catch (Exception e) {
            System.out.println(""+e);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tfJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJumlahKeyTyped
        // TODO add your handling code here:
        keyType();
    }//GEN-LAST:event_tfJumlahKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setVisible(false);
        new MenuUtama().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void tfKeteranganPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfKeteranganPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKeteranganPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GajiTambahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GajiTambahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GajiTambahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GajiTambahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GajiTambahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private com.toedter.calendar.JDateChooser dcTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> n_karyawan;
    private javax.swing.JTable tbPemasukkan;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfKeterangan;
    private javax.swing.JTextField tfKode;
    // End of variables declaration//GEN-END:variables
}
